home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_1/urls.py
from django.urls import path, include
from . import views
#url for app
urlpatterns = [
    path('', views.index, name='index'),
]

lab_3/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

#url for app, add your URL Configuration
app_name = 'profile'

urlpatterns = [
    #TODO Implement this
    path('', views.index, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    path('course/add', views.course_add, name='add_course'),
    path('course/update/<str:pk>', views.course_update, name='update_course'),
    path('course/delete/<str:pk>', views.course_delete, name='delete_course'),
    path('course/detail/<str:pk>', views.course_detail, name='detail_course'),
    path('course/', views.course, name='course'),
    path('activity/', views.activity, name='activity'),
    path('register/<str:pk>', views.register, name='register'),
]

praktikum/urls.py
from django.urls import path, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_3.urls as lab_3


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab_3.urls')),
    path('story-1/', include('lab_1.urls')),

]

home/models.py
from django.db import models

# Create your models here.

lab_1/models.py
from django.db import models

# Create your models here.

lab_3/models.py
from django.db import models

# Create your models here.

class Activity(models.Model):

    class Meta:
        verbose_name_plural = 'Activities'
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Person(models.Model):
    
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

class Course(models.Model):
    name = models.CharField(max_length=50)
    lecturer = models.CharField(max_length=80)
    credit = models.CharField(max_length=10)
    description = models.TextField()
    year = models.CharField(max_length=20)
    room = models.CharField(max_length=10)

    def __str__(self):
        return self.name


    

lab_3/forms.py
from django import forms
from lab_3.models import Course, Activity, Person

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = (
            'name',
        )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = (
            'name',
            'lecturer',
            'credit',
            'description',
            'year',
            'room',
        )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'lecturer': forms.TextInput(attrs={'class': 'form-control'}),
            'credit': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'year': forms.TextInput(attrs={'class': 'form-control'}),
            'room': forms.TextInput(attrs={'class': 'form-control'}),
        }

home/views.py
from django.shortcuts import render
from lab_1.views import mhs_name

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = "welcome to my ppw-lab"

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'homepage.html', response)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'faris ardhafa' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2000, 2, 8) #TODO Implement this, format (Year, Month, Date)
npm = 1906400293 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_3/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import inlineformset_factory, modelformset_factory
from lab_3.forms import CourseForm, PersonForm
from lab_3.models import Course, Activity, Person
#TODO Implement

def index(request):
    return render(request, 'index.html')

def gallery(request):
    return render(request, 'gallery.html')

def course_add(request):
    form = CourseForm()
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('profile:course')
    context = {
        'form': form
    }
    return render(request, 'form.html', context)

def course_update(request, pk):
    course = Course.objects.get(id=pk)
    form = CourseForm(instance=course)
    if request.method == "POST":
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('profile:course')
    context = {
        'course': course,
        'form': form
    }
    return render(request, 'form.html', context)

def course_delete(request, pk):
    course = Course.objects.get(id=pk)
    if request.method == "POST":
        course.delete()
        return redirect('profile:course')
    context = {
        'course': course
    }
    return render(request, 'delete.html', context)

def course_detail(request, pk):
    course = Course.objects.get(id=pk)
    context = {
        'course': course
    }
    return render(request, 'detail.html', context)

def course(request):
    course = Course.objects.all();
    context = {
        'course': course
    }
    return render(request, 'course.html', context)

def activity(request):
    activity_1 = Person.objects.filter(activity__name="DOTA");
    activity_2 = Person.objects.filter(activity__name="LoL");
    activity_3 = Person.objects.filter(activity__name="Genshin");
    context = {
        'activity_1': activity_1,
        'activity_2': activity_2,
        'activity_3': activity_3,
    }
    return render(request, 'activity.html', context)

def register(request, pk):
    PersonFormSet = inlineformset_factory(Activity, Person, fields=('name',))
    activity = Activity.objects.get(id=pk)
    formset = PersonFormSet(instance=activity)
    if request.method == "POST":
        formset = PersonFormSet(request.POST, instance=activity)
        if formset.is_valid():
            formset.save()
            return redirect('profile:activity')
    return render(request, 'register.html', {'formset':formset})

home/templates/homepage.html
{% extends "base.html" %}
{% block content %}
<style>
    body,
    html {
        height: 100%;
        margin: 0;
    }

    .caption {
        position: absolute;
        left: 0;
        top: 50%;
        width: 100%;
        text-align: center;
        font-family: monospace;
        color: #000;
    }

    .caption span.border {
        background-color: rgba(206, 166, 211, 0.4);
        ;
        color: #fff;
        padding: 18px;
        font-size: 25px;
        letter-spacing: 5px;
    }

    .bg {
        /* The image used */
        background-image: url("https://pbs.twimg.com/media/EhtPqNrVoAEPw8T?format=jpg");

        /* Full height */
        height: 100%;

        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>

<div class="bg">
    <div class="caption">
        <span class="border">hello, this is {{ name }}, {{ content }}</span><br>
    </div>
</div>
{% endblock %}

home/templates/index_lab2test.html
{% extends "base.html" %}
{% block content %}
<style>
    body,
        html {
            height: 100%;
            margin: 0;
        }

        .caption {
        position: absolute;
        left: 0;
        top: 50%;
        width: 100%;
        text-align: center;
        font-family: monospace;
        color: #000;
        }

        .caption span.border {
        background-color: rgba(206, 166, 211, 0.4);;
        color: #fff;
        padding: 18px;
        font-size: 25px;
        letter-spacing: 5px;
        }

        .bg {
            /* The image used */
            background-image: url("https://pbs.twimg.com/media/EhtPqNrVoAEPw8T?format=jpg");

            /* Full height */
            height: 100%;

            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
</style>

<div class="bg">
    <div class="caption">
        <span class="border">hello, this is {{ name }}, {{ content }}</span><br>
    </div>
</div>
{% endblock %}

lab_1/templates/index_lab1.html
{% extends "base.html" %}
{% block content %}
    <h1>Hello my name is {{ name }}</h1>
    <article>Npm: {{ npm }}</article>
    <article>I am {{ age }} years old</article>
{% endblock %}

lab_3/templates/activity.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'activity.css' %}">

<div class="container-fluid">
    <div class="header">
        <h1 class="text-center" style="color: #63526C;">My Activity</h1>
    </div>
    <div class="row">
        <div class="column text-center">
            <h3>Mabar DOTA</h3>
            <img src="{% static 'dota-2-logo.0.jpg' %}" style="width:100%">
            <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/1">Register</a>
            <table class="table">
                <thead class="thead-dark">
                    <th scope="col">Nama Teman</th>
                </thead>
                <tbody>
                    {% for i in activity_1 %}
                    <tr>
                        <td class="table-dark">{{ i.name }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="column text-center">
            <h3>Mabar LoL</h3>
            <img src="{% static 'Home-page.jpg' %}" style="width:100%">
            <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/2">Register</a>
            <table class="table">
                <thead class="thead-dark">
                    <th scope="col">Nama Teman</th>
                </thead>
                <tbody>
                    {% for i in activity_2 %}
                    <tr>
                        <td class="table-dark">{{ i.name }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="column text-center">
            <h3>Mabar Genshin</h3>
            <img src="{% static 'Genshin-Impact-image-new-1.png' %}" style="width:100%">
            <a class="btn btn-dark mr-2 mt-2 mb-5" href="/register/3">Register</a>
            <table class="table">
                <thead class="thead-dark">
                    <th scope="col">Nama Teman</th>
                </thead>
                <tbody>
                    {% for i in activity_3 %}
                    <tr>
                        <td class="table-dark">{{ i.name }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

lab_3/templates/course.html
{% extends "base.html" %}
{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <h1 class="text-center" style="color: #63526C">My Courses</h1>
        <table class="table">
            <thead class="thead-dark">
                <th scope="col-2">Mata Kuliah</th>
                <th scope="col-2">Options</th>
            </thead>
            <tbody>
                {% for i in course %}
                <tr>
                    <td class="table-dark">{{ i.name }} </td>
                    <td class="table-dark">
                        <a class="btn btn-success mr-1 mb-1" href="{% url 'profile:detail_course' i.id %}">Detail</a> 
                        <a class="btn btn-info mr-1 mb-1" href="{% url 'profile:update_course' i.id %}">Update</a>
                        <a class="btn btn-danger mr-1 mb-1" href="{% url 'profile:delete_course' i.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
    
{% endblock %}

lab_3/templates/delete.html
{% extends "base.html" %}
{% block content %}

<div class="delete-form">
    <form action="{% url 'profile:delete_course' course.id %}" method="POST">
        {% csrf_token %}
        <div class="row justify-content-center">
            <h1 class="text-center" style="color: #63526C; margin-top: 60px;">Delete {{ course.name }}?</h1>

            <a class="btn btn-primary mr-2" href="{% url 'profile:course' %}">Cancel</a>
            <button type="submit" class="btn btn-danger">Confirm</button>
        </div>
    </form>
</div>

{% endblock %}

lab_3/templates/detail.html
{% extends "base.html" %}
{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <h1 class="text-center" style="color: #63526C">My Courses</h1>
        <table class="table">
                <tr>
                    <td class="table-dark">Mata Kuliah</td>
                    <td class="table-dark">{{ course.name }} </td>
                </tr>
                <tr>
                    <td class="table-dark">Dosen</td>
                    <td class="table-dark">{{ course.lecturer }} </td>
                </tr>
                <tr>
                    <td class="table-dark">Deskripsi</td>
                    <td class="table-dark">{{ course.description }} </td>
                </tr>
                <tr>
                    <td class="table-dark">Semester</td>
                    <td class="table-dark">{{ course.year }} </td>
                </tr>
                <tr>
                    <td class="table-dark">SKS</td>
                    <td class="table-dark">{{ course.credit }} </td>
                </tr>
                <tr>
                    <td class="table-dark">Ruang</td>
                    <td class="table-dark">{{ course.room }} </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

lab_3/templates/form.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid">
    <form action="" class="main-form" id="form" method="POST">
        <h1 class="text-center">Course Forms</h1>
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="name">Mata Kuliah</label>
                    {{ form.name }}
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="lecturer">Dosen</label>
                    {{ form.lecturer }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <label for="description">Deskripsi</label>
                    {{ form.description }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <label for="year">Semester/Tahun Ajaran</label>
                    {{ form.year }}
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="credit">SKS</label>
                    {{ form.credit }}
                </div>
            </div>
            <div class="col-3">
                <div class="form-group">
                    <label for="room">Ruang</label>
                    {{ form.room }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>

{% endblock %}

lab_3/templates/gallery.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'gallery.css' %}">

<div class="container-fluid">
    <div class="header">
        <h1 class="text-center" style="color: #63526C;">My Gallery</h1>
    </div>
    <div class="row ">
        <div class="column">
            <img src="{% static 'EjabhrpUcAcpHr0.jpg' %}" style="width:100%">
        </div>
        <div class="column">
            <img src="{% static 'EjaXHMlVkAAeUw9.jpg' %}" style="width:100%">
        </div>
        <div class="column">
            <img src="{% static 'jojinectar-819x1024.jpg' %}" style="width:100%">
        </div>
    </div>
</div>
{% endblock %}

lab_3/templates/index.html
{% extends "base.html" %}
{% block content %}

<section class="landing-page" id="home">
    <div class="container-1">
        <div class="landing-page-column">
            <div id="landing-page-caption1">
                Hello, I'm
            </div>
            <div id="landing-page-caption2">
                Faris Ardhafa
            </div>
        </div>
    </div>
</section>

<div class="section-a" id="resume">
    <h1>Resume</h1>
    <div class="container-2">
        <div class="education">
            <h3>Education</h3>
            <div id="section-a-content1">
                <h4>High School</h4>
                <h3>78 Senior High School, Jakarta</h3>
                <h5>2017 - 2019</h5>
            </div>
            <div id="section-a-content3">
                <h4>University</h4>
                <h3>Faculty of Computer Science, University of Indonesia</h3>
                <h5>2019 - Present</h5>
            </div>
        </div>
        <div class="experiences">
            <h3>Experiences</h3>
            <div id="section-a-content2">
                <h4>COMPFEST</h4>
                <h3>Finance Staff</h3>
                <h5>2020</h5>
            </div>
        </div>
    </div>
</div>

<section class="section-b" id="about">
    <h1>About Me</h1>
    <div class="container-3">
        <div class="contact">
            <div id="section-b-content1">
                <h2>Contact</h2>
                <h3>EMAIL</h3>
                <h4>frsardhafa@gmail.com</h4>
                <h3>PHONE</h3>
                <h4>+62 878 8605 4739</h4>
                <h3>ADDRESS</h3>
                <h4>Taman Alfa Indah B5/6, Joglo, Kembangan, West Jakarta, 11640</h4>
            </div>
        </div>
        <div class="about">
            <div id="section-b-content2">
                <p>Hi, my name is Faris Ardhafa. I’m a student at University of Indonesia. I specialize in Python and
                    Java language.
                    Currently I’m learning web development and this profile is one of the example. I will add more of my
                    skills and
                    experiences in the future. Thank you and have a great day!
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

 

lab_3/templates/register.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid">
    <form action="" class="main-form" id="form" method="POST">
        <h1 class="text-center">Register Forms</h1>
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="form-group">
                    {{ formset.management_form }}
                    {% for form in formset %}
                    {{ form.as_p }}
                    {% endfor %}
                    <br>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Roboto fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">


    <title>Profile</title>
</head>

<body>
<nav class="navbar navbar-expand-lg site-navbar navbar-light bg-light" id="pb-navbar">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09"
            aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample09">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#resume">Resume</a></li>
                <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'profile:gallery' %}">Galery</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'profile:course' %}">Course</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'profile:activity' %}">Activity</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'profile:add_course' %}">Course Forms</a></li>
                <li class="nav-item"><a class="nav-link" href="/story-1">Story 1</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
</body>
</html>